call cordova plugin add phonegap-plugin-barcodescanner
call cordova plugin add phonegap-plugin-mobile-accessibility
call cordova plugin add cordova-plugin-camera
call cordova plugin add cordova-plugin-device
call cordova plugin add cordova-plugin-file
call cordova plugin add cordova-plugin-ftp
call cordova plugin add skwas-cordova-plugin-datetimepicker    
call cordova plugin add  https://github.com/dpa99c/phonegap-launch-navigator
call cordova plugin add cordova-plugin-call-number